import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma'; // Assuming you have a DB connection

// ---- Types ----

export interface StreamSource {
  id?: string;
  url: string;
  bitrate: number;
  resolution: string;
  kind?: 'sub' | 'dub';
  language?: string;
  audioLang?: string;
  label?: string;
  type?: string; // e.g., 'hls' or 'mp4'
}

export interface SubtitleTrack {
  lang: string;
  label: string;
  url?: string;
}

export interface StreamPayload {
  animeId: string;
  episodeId: string;
  streamUrl: string;
  sources?: StreamSource[];
  subtitles?: SubtitleTrack[];
  meta?: {
    title: string;
    duration: number;
    thumbnail: string;
  };
}

// ---- Route ----

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const animeId = searchParams.get('animeId');
  const episodeId = searchParams.get('episodeId');

  if (!animeId || !episodeId) {
    return NextResponse.json(
      { error: 'Missing animeId or episodeId' },
      { status: 400 }
    );
  }

  try {
    // A. Fetch Episode Data from DB
    // NOTE: title/duration/thumbnail are now selected since they're used in `meta` below.
    // Adjust field names here to exactly match your Prisma schema.
    const episode = await prisma.episode.findUnique({
      where: { id: episodeId },
      select: {
        streamUrl: true,
        drmKey: true, // Optional: for Widevine/FairPlay. See note below on shape.
        subtitles: true,
        quality: true,
        bitrate: true,
        title: true,
        duration: true,
        thumbnail: true,
      },
    });

    if (!episode) {
      return NextResponse.json({ error: 'Episode not found' }, { status: 404 });
    }

    // B. Validate Stream URL (Ping the CDN)
    const isAccessible = await checkStreamHealth(episode.streamUrl);
    if (!isAccessible) {
      return NextResponse.json(
        { error: 'Stream temporarily unavailable', retryAfter: 30 },
        { status: 503 }
      );
    }

    // C. Normalize subtitles into SubtitleTrack[] shape
    const subtitles: SubtitleTrack[] = normalizeSubtitles(episode.subtitles);

    // D. Build sources[] (players generally expect an array, not just one streamUrl)
    const sources: StreamSource[] = [
      {
        url: episode.streamUrl,
        bitrate: episode.bitrate ?? 0,
        resolution: episode.quality ?? 'auto',
        type: 'hls',
      },
    ];

    // E. Return Secure Stream Data
    return NextResponse.json({
      success: true,
      data: {
        animeId,
        episodeId,
        // For production, use signed URLs generated by your CDN (e.g., Cloudflare R2 + JWT)
        streamUrl: episode.streamUrl,
        sources,
        subtitles,
        drmConfig: buildDrmConfig(episode.drmKey),
        meta: {
          title: episode.title,
          duration: episode.duration,
          thumbnail: episode.thumbnail,
        },
      } satisfies StreamPayload,
    });
  } catch (error) {
    console.error('Stream API Error:', error);
    return NextResponse.json(
      { error: 'Internal stream resolution error' },
      { status: 500 }
    );
  }
}

// ---- Helpers ----

/**
 * Check if the HLS playlist/segment is accessible.
 * Many CDNs reject HEAD requests for HLS content (403/405) even though GET works.
 * Using a ranged GET avoids downloading the whole playlist while still being reliable.
 */
async function checkStreamHealth(url: string): Promise<boolean> {
  try {
    const response = await fetch(url, {
      method: 'GET',
      headers: { Range: 'bytes=0-0' },
      next: { revalidate: 0 },
    });
    return response.ok || response.status === 206;
  } catch {
    return false;
  }
}

/**
 * drmKey shape depends on your schema:
 * - If it's a scalar string column, this returns a minimal config using that string as keyId only.
 * - If it's JSON with { keyId, certUrl }, that shape is used directly.
 * Adjust this to match your actual Prisma model.
 */
function buildDrmConfig(
  drmKey: unknown
): { type: 'widevine'; keyId: string; certificateUrl?: string } | null {
  if (!drmKey) return null;

  if (typeof drmKey === 'string') {
    return { type: 'widevine', keyId: drmKey };
  }

  if (typeof drmKey === 'object' && drmKey !== null) {
    const obj = drmKey as Record<string, unknown>;
    return {
      type: 'widevine',
      keyId: String(obj.keyId ?? ''),
      certificateUrl: obj.certUrl ? String(obj.certUrl) : undefined,
    };
  }

  return null;
}

/**
 * Normalizes whatever `episode.subtitles` looks like in your DB
 * (JSON array, string array, etc.) into SubtitleTrack[].
 * Adjust this to match your actual Prisma model's shape.
 */
function normalizeSubtitles(subtitles: unknown): SubtitleTrack[] {
  if (!subtitles) return [];
  if (!Array.isArray(subtitles)) return [];

  return subtitles
    .map((s): SubtitleTrack | null => {
      if (typeof s === 'string') {
        return { lang: s, label: s };
      }
      if (typeof s === 'object' && s !== null) {
        const obj = s as Record<string, unknown>;
        return {
          lang: String(obj.lang ?? obj.language ?? 'unknown'),
          label: String(obj.label ?? obj.lang ?? 'Subtitle'),
          url: obj.url ? String(obj.url) : undefined,
        };
      }
      return null;
    })
    .filter((s): s is SubtitleTrack => s !== null);
}
