import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma'; // Assuming you have a DB connection

// 1. Define the Stream Quality Interface
interface StreamQuality {
  url: string;
  bitrate: number;
  resolution: string;
}

// 2. The API Route
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const animeId = searchParams.get('animeId');
  const episodeId = searchParams.get('episodeId');

  if (!animeId || !episodeId) {
    return NextResponse.json(
      { error: 'Missing animeId or episodeId' },
      { status: 400 }
    );
  }

  try {
    // A. Fetch Episode Data from DB
    const episode = await prisma.episode.findUnique({
      where: { id: episodeId },
      select: {
        streamUrl: true,
        drmKey: true, // Optional: for Widevine/FairPlay
        subtitles: true,
        quality: true,
        bitrate: true,
      }
    });

    if (!episode) {
      return NextResponse.json({ error: 'Episode not found' }, { status: 404 });
    }

    // B. Validate Stream URL (Ping the CDN)
    const isAccessible = await checkStreamHealth(episode.streamUrl);
    if (!isAccessible) {
      return NextResponse.json(
        { error: 'Stream temporarily unavailable', retryAfter: 30 },
        { status: 503 }
      );
    }

    // C. Return Secure Stream Data
    return NextResponse.json({
      success: true,
      data: {
        animeId,
        episodeId,
        // For production, use signed URLs generated by your CDN (e.g., Cloudflare R2 + JWT)
        streamUrl: episode.streamUrl, 
        subtitles: episode.subtitles || [],
        drmConfig: episode.drmKey ? {
          type: 'widevine',
          keyId: episode.drmKey.keyId,
          certificateUrl: episode.drmKey.certUrl
        } : null,
        // Metadata for the player UI
        meta: {
          title: episode.title,
          duration: episode.duration,
          thumbnail: episode.thumbnail
        }
      }
    });

  } catch (error) {
    console.error('Stream API Error:', error);
    return NextResponse.json(
      { error: 'Internal stream resolution error' },
      { status: 500 }
    );
  }
}

// Helper: Check if the HLS playlist is accessible
async function checkStreamHealth(url: string): Promise<boolean> {
  try {
    const response = await fetch(url, { method: 'HEAD', next: { revalidate: 0 } });
    return response.ok;
  } catch {
    return false;
  }
}

export interface StreamSource {
  id?: string;
  url: string;
  bitrate: number;
  resolution: string;
  kind?: 'sub' | 'dub';
  language?: string;
  audioLang?: string;
  label?: string;
  type?: string; // <-- Add this property
}

export interface StreamPayload {
  animeId: string;
  episodeId: string;
  streamUrl: string;
  sources?: StreamSource[]; // <-- Added this property
  subtitles?: any[];
  meta?: {
    title: string;
    duration: number;
    thumbnail: string;
  };
}
